# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8030af2145098eb0ede9e00f01ede6b0f6298fc1e49c7d0139e440de14e1114e5de535aed76297f1c57136e8ac37e8145a3fc67ce67228068d9069a93acf159b

test:
  secret_key_base: fbc98c39fc11c936d49a46770b17b4ce632171d21f24c9b776a6e7831fbebaf2b57bb77966a7e3272d381b34ee863499ad60de9959130d3b7ba43a2ddd663a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
